[package]
name = "qsc_llvm"
version = "0.0.0"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
qsc_hir = { path = "../qsc_hir" }
either = "1.8.1"
log = "0.4.17"
