[package]
name = "qsc_codegen"
version = "0.0.0"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

[dev-dependencies]
expect-test = { workspace = true }
